#!/usr/bin/env python3
"""Generate VMD visualization files from existing aligned output."""

from pathlib import Path


def write_trajectory(xyz_files, output_path):
    """Concatenate XYZ files into a single trajectory file."""
    with open(output_path, 'w') as out:
        for xyz_file in xyz_files:
            with open(xyz_file) as f:
                out.write(f.read())


def write_vmd_script(traj_path, vmd_path, n_frames, family_name):
    """Write a VMD visualization script."""
    # Convert to Windows path for VMD
    traj_abs = traj_path.resolve()
    traj_windows = str(traj_abs).replace('/', '\\')
    if traj_windows.startswith('\\mnt\\c'):
        traj_windows = 'C:' + traj_windows[6:]

    script = f'''#!/usr/local/bin/vmd
# VMD script for {family_name}
# Auto-generated by ELISA SPAWNS
# {n_frames} aligned molecules

# Load trajectory
mol new {{{traj_windows}}} type xyz first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all

# Delete default representation
mol delrep 0 top

# Representation 1: Reference (frame 0) - transparent
mol representation CPK 1.0 0.3 12.0 12.0
mol color Index
mol selection {{all}}
mol material Transparent
mol addrep top
mol drawframes top 0 {{0}}

# Representation 2: Current frame - opaque
mol representation CPK 1.0 0.3 12.0 12.0
mol color Index
mol selection {{all}}
mol material Opaque
mol addrep top

# Set molecule name
mol rename top {{{family_name}}}

# Display settings
display projection Perspective
display depthcue on
axes location Off
color Display Background white

# Go to frame 1 (first aligned molecule)
animate goto 1

display resetview

puts "=============================================="
puts "{family_name}"
puts "=============================================="
puts "Frame 0: Reference (template)"
puts "Frames 1-{n_frames-1}: Aligned molecules"
puts ""
puts "Transparent: Reference"
puts "Opaque: Current frame (use slider)"
puts "=============================================="
'''

    with open(vmd_path, 'w') as f:
        f.write(script)


def main():
    output_dir = Path("aligned_output")

    if not output_dir.exists():
        print("Error: output/ folder not found. Run the alignment first.")
        return

    # Find all family folders
    family_dirs = sorted(output_dir.glob("family_*"))

    if not family_dirs:
        print("Error: No family folders found in output/")
        return

    print(f"Found {len(family_dirs)} family folders")
    print()

    for family_dir in family_dirs:
        if not family_dir.is_dir():
            continue

        family_name = family_dir.name
        xyz_files = sorted(family_dir.glob("*.xyz"))

        if not xyz_files:
            print(f"  {family_name}: No XYZ files found, skipping")
            continue

        # Create trajectory file
        traj_path = output_dir / f"{family_name}.xyz"
        write_trajectory(xyz_files, traj_path)

        # Create VMD script
        vmd_path = output_dir / f"{family_name}.vmd"
        write_vmd_script(traj_path, vmd_path, len(xyz_files), family_name)

        print(f"  {family_name}: {len(xyz_files)} molecules -> {traj_path.name}, {vmd_path.name}")

    print()
    print("Done! VMD files written to output/")
    print("Double-click any .vmd file to visualize in VMD")


if __name__ == "__main__":
    main()
